name: AwesomeLevels
main: com.emiv.awesomelevels.Main
version: 1.6
api-version: 1.16
softdepend: [Vault]
commands:
  level:
    aliases: [levels, levelup, rank, rankup]
    description: Main level command
  alreload:
    aliases:
    description: Reload the configs